# Generated by Django 3.2.13 on 2022-06-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_id', models.IntegerField(default=0)),
                ('condition', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('drug_name', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
                ('review', models.TextField()),
                ('unique_id', models.IntegerField(default=0)),
                ('useful_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PharmaSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmasale_id', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('atc_code', models.FloatField()),
                ('atc_classification', models.CharField(max_length=200)),
                ('drug_classification', models.CharField(max_length=200)),
            ],
        ),
    ]
